site_name: Alice Braun
site_description: Academic CV
site_author: Alice Braun
site_url: https://alicebraun.github.io/
theme:
  name: material
  palette:
    - scheme: slate
      primary: deep purple
      accent: deep purple
  font:
    text: DM Sans
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate


nav:
  - CV: index.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - attr_list
